# Generated by Django 4.1.1 on 2022-10-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjob',
            name='experiencerequired',
            field=models.CharField(choices=[('0-1', '0-1'), ('1-2', '1-2'), ('2-3', '2-3'), ('3-4', '3-4'), ('4-5', '4-5')], max_length=20),
        ),
        migrations.AlterField(
            model_name='postjob',
            name='jobtitle',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='postjob',
            name='jobtype',
            field=models.CharField(choices=[('parttime', 'parttime'), ('fulltime', 'fulltime')], max_length=20),
        ),
    ]
