# Generated by Django 4.1.1 on 2022-10-01 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_alter_postjob_experiencerequired_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='postjob',
            new_name='profilepost',
        ),
    ]
