# Generated by Django 4.1.1 on 2022-10-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_alter_profilepost_jobtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='regmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('qualification', models.CharField(max_length=25)),
                ('phoneno', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('cspassword', models.CharField(max_length=20)),
            ],
        ),
    ]
