# Generated by Django 4.1.1 on 2022-10-13 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_regmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regmodel',
            name='cspassword',
        ),
    ]
