# Generated by Django 4.1.1 on 2022-10-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_remove_regmodel_cspassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='applyjobmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('exp', models.IntegerField()),
                ('resume', models.FileField(upload_to='')),
            ],
        ),
    ]
