# Generated by Django 4.1.1 on 2022-10-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0007_applyjobmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='applyjobmodel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('exp', models.IntegerField()),
                ('resume', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='applyjobmodel',
        ),
    ]
